#!/usr/bin/env python3
"""Generate SS-BB-ADPLL DTC assets (ref2 plan):
  netlist/va/pll_dtc_code.va  — 10-bit code -> 1023 thermometer decoder (passthrough)
  netlist/inc/dtc_10b_ss.scs  — dtc_10b with 14 external ports, decoder embedded

vs gen_dtc_ref.py (Wu-plan A'): the QE->code decoder (pll_dtc_decoder_10b) is
replaced by a pure 10-bit thermometer (code value k enables units 0..k-1, i.e.
c<i>=1 when cv>i); LMS ports (CKFB KDTC EPSC SEL ALT VDCC RDCC) removed, CODE0-9
added. Delay line (R0/switch+0.5fF units/reset/buffer) unchanged — same DTC.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_VA = ROOT / "netlist" / "va" / "pll_dtc_code.va"
OUT_SCS = ROOT / "netlist" / "inc" / "dtc_10b_ss.scs"

NSW = 1023


def mos(model, nf):
    return (f"{model} l=16n nfin=2 w=58n multi=1 nf={nf}  sd=74n sa=90n sb=90n "
            "ploda1=16n ploda2=0 ploda3=0 plodb1=16n \\\n"
            "        plodb2=0 plodb3=0 nf_flag=1 smbt=1M smbb=1M dinsaflag=0 ppitch=0 \\\n"
            "        spot=103n spob=103n spotl1=103n spobl1=103n spotl2=103n \\\n"
            "        spobl2=103n spotr1=103n spobr1=103n spotr2=103n spobr2=103n")


def port_rows(names):
    """Wrap port names 16 per line with continuation, like the old decoder."""
    rows = []
    for i in range(0, len(names), 16):
        row = "    " + ", ".join(names[i:i + 16])
        rows.append(row)
    return ",\n".join(rows)


def gen_va():
    cnames = [f"c{i}" for i in range(NSW)]
    lines = [
        "// pll_dtc_code.va — 10-bit thermometer decoder (1023 outputs), generated",
        "// code value cv enables units 0..cv-1: c<i> = 1 when cv > i (pure passthrough,",
        "// replaces the Wu QE->code decoder for the ref2 SS-BB fractional accumulator)",
        "`include \"constants.vams\"",
        "`include \"disciplines.vams\"",
        "",
        f"module pll_dtc_code(code0, code1, code2, code3, code4, code5, code6, code7, code8, code9,",
        port_rows(cnames) + ");",
        "inout code0, code1, code2, code3, code4, code5, code6, code7, code8, code9;",
        "electrical code0, code1, code2, code3, code4, code5, code6, code7, code8, code9;",
    ]
    for cn in cnames:
        lines.append(f"inout {cn};")
        lines.append(f"electrical {cn};")
    lines += [
        "",
        "parameter real vth = 0.5;",
        "",
        "integer cv, i;",
        "",
        "analog begin",
        "    cv = 0;",
        "    if (V(code0) > vth) cv = cv + 1;",
        "    if (V(code1) > vth) cv = cv + 2;",
        "    if (V(code2) > vth) cv = cv + 4;",
        "    if (V(code3) > vth) cv = cv + 8;",
        "    if (V(code4) > vth) cv = cv + 16;",
        "    if (V(code5) > vth) cv = cv + 32;",
        "    if (V(code6) > vth) cv = cv + 64;",
        "    if (V(code7) > vth) cv = cv + 128;",
        "    if (V(code8) > vth) cv = cv + 256;",
        "    if (V(code9) > vth) cv = cv + 512;",
    ]
    for i in range(NSW):
        lines.append(f"    V(c{i}) <+ transition((cv > {i}) ? 0.8 : 0.0, 0, 50p);")
    lines += [
        "end",
        "endmodule",
        "",
    ]
    OUT_VA.write_text("\n".join(lines))
    print(f"wrote {OUT_VA} ({len(lines)} lines)")


def xdec_line():
    L = ["Xdec (CODE0 CODE1 CODE2 CODE3 CODE4 CODE5 CODE6 CODE7 CODE8 CODE9 \\"]
    for i in range(0, NSW, 16):
        row = " ".join(f"c{j}" for j in range(i, min(i + 16, NSW)))
        L.append("    " + row + " \\")
    L.append("    ) pll_dtc_code vth=0.5")
    return "\n".join(L)


def gen_scs():
    lines = [
        "// dtc_10b_ss.scs — 10-bit RC DTC for SS-BB-ADPLL (ref2) — generated by tools/gen_dtc_ss.py",
        "// subckt ports = 14 external signals (CK_IN CK_OUT VDD VSS CODE0..CODE9);",
        "// 1023 switch gates are internal c<i> nets driven by embedded decoder pll_dtc_code",
        "// (10-bit thermometer passthrough; fractional accumulator drives CODE in frac mode,",
        "// constant 0 in integer mode). Delay line identical to dtc_10b:",
        "// unit: NMOS switch nf=2 + CLSB=0.5fF; R0 rhim 2.3u x 2u; Tres ~330fs, full DR ~337ps;",
        "// reset: CK_IN low -> CKXB high -> MRST_D slams VDLY to VSS (edge-dropping bug fix)",
        "subckt dtc_10b_ss (CK_IN CK_OUT VDD VSS CODE0 CODE1 CODE2 CODE3 CODE4 CODE5 CODE6 CODE7 CODE8 CODE9)",
        "",
        xdec_line(),
        "",
        "R0 (CK_IN VDLY) rhim l=2.3e-06 w=2e-06 multi=1",
        "MNI (CKXB CK_IN VSS VSS) " + mos("nch_svt_mac", 1),
        "MPI (CKXB CK_IN VDD VDD) " + mos("pch_svt_mac", 1),
        "MRST_D (VDLY CKXB VSS VSS) " + mos("nch_svt_mac", 2),
        "",
    ]
    for i in range(NSW - 1, -1, -1):
        lines.append(f"U{i} (VDLY c{i} UCAP{i} VSS) " + mos("nch_svt_mac", 2))
        lines.append(f"C{i} (UCAP{i} VSS) capacitor c=5e-16")
    lines += [
        "",
        "MN1 (CK_OUT VDLY VSS VSS) " + mos("nch_svt_mac", 8),
        "MP1 (CK_OUT VDLY VDD VDD) " + mos("pch_svt_mac", 8),
        "ends dtc_10b_ss",
        "",
    ]
    OUT_SCS.write_text("\n".join(lines))
    print(f"wrote {OUT_SCS} ({len(lines)} lines)")


if __name__ == "__main__":
    gen_va()
    gen_scs()
