#!/usr/bin/env python3
"""Generate netlist/inc/vco_c_dac.scs — SS-BB-ADPLL single-core VCO (ref2 plan).

Same 0.5V Plan C core as vco_c.scs (cross-coupled pair nf=16, Ls tail inductor,
1.5nH loads, CF bank nr=174) but:
- SINGLE core (no dual-core wrapper, no EN2/coupling switches) — vco_x_c_dac
- varactor control = two ideal DAC outputs direct-driving the moscap bulks:
    VC1 (coarse DAC1): moscap nfin=24 per side  -> KVCO ~206MHz/V (Plan C proven
      direct-connect measurement, monotonic 0.15-0.53V, no rectification pump)
    VC2 (fine DAC2):   moscap nfin=2  per side  -> KVCO ~5-20MHz/V (calibrated)
- no enable switches, no 1G bleeders (DAC ideal source drives the bulk directly —
  eliminates the wp2/wp4/wp5 switch-threshold root cause entirely)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "netlist" / "inc" / "vco_c_dac.scs"

NCH = ("nch_ulvt_mac l=16n nfin=2 w=58n multi=1 sd=74n sa=90n sb=90n "
       "ploda1=16n ploda2=0 ploda3=0 plodb1=16n plodb2=0 plodb3=0 nf_flag=1 "
       "smbt=1M smbb=1M dinsaflag=0 ppitch=0 spot=103n spob=103n "
       "spotl1=103n spobl1=103n spotl2=103n spobl2=103n spotr1=103n "
       "spobr1=103n spotr2=103n spobr2=103n")
MOSCAP = ("moscap_rf wr=538n lr=200n gr=2 br=2 multi=1 "
          "sobn=470n sobs=470n sobw=684n sobe=684n")
LS_L = "2n"
CF_NR = 174          # recalibrate after varactor load change (target 8.0G center)
C1_NFIN = 24         # coarse varactor (DAC1) per side
C2_NFIN = 2          # fine varactor (DAC2) per side


def mos(name, d, g, s, b, nf):
    return f"{name} ({d} {g} {s} {b}) {NCH} nf={nf}"


def cfmom(name, plus, minus, shield, nr):
    return (f"{name} ({plus} {minus} {shield}) cfmom_wo_p80 dmflag=0 lr=1u "
            f"multi=1 mxd_flag=0 nr={nr} n_mxa=2 shield=2 spm=3 stm=1 "
            f"vapmod=2 grflag=1 gdis_t=185n gdis_b=185n gdis_l=102n gdis_r=102n")


def gen():
    L = [
        "// vco_c_dac.scs — generated by tools/gen_vco_c_dac.py (ref2 SS-BB-ADPLL single core)",
        "// core supply VDDC=0.5V from LDO (ldo_05.scs); logic domain VDD=0.8V",
        "// VC1/VC2 = ideal DAC outputs (0-0.5V) direct-driving varactor bulks:",
        "//   VC1 coarse: nfin=24 moscap/side (~206MHz/V)  <- DAC1 (7-bit)",
        "//   VC2 fine:   nfin=2  moscap/side (~5-20MHz/V) <- DAC2 (9-bit)",
        "// no enable switches / no bleeders (switch-threshold root cause removed)",
        "",
        "subckt vco_x_c_dac (VDD VDDC VSS OUTP OUTN VC1 VC2)",
        mos("MN1", "OUTP", "OUTN", "TAIL", "VSS", 16),
        mos("MN0", "OUTN", "OUTP", "TAIL", "VSS", 16),
        f"Ls (TAIL VSS) inductor l={LS_L} r=1",
        "L1 (VDD OUTN) inductor l=1.5n r=2",
        "L0 (VDD OUTP) inductor l=1.5n r=2",
        "Cbyp (VDD VSS) capacitor c=10p",
    ]
    for i in range(12):
        plus = "OUTP" if i in (0, 6) else "OUTN"
        minus = "OUTN" if i in (0, 6) else f"net{i:02d}"
        L.append(cfmom(f"CF{i}", plus, minus, "VSS", CF_NR))
    # DAC-driven varactors: gate=tank, bulk=gnode=DAC output (moscap_rf 3-terminal)
    L.append(f"C1p_mv (OUTP VC1 VC1) {MOSCAP} nfin={C1_NFIN}")
    L.append(f"C1n_mv (OUTN VC1 VC1) {MOSCAP} nfin={C1_NFIN}")
    L.append(f"C2p_mv (OUTP VC2 VC2) {MOSCAP} nfin={C2_NFIN}")
    L.append(f"C2n_mv (OUTN VC2 VC2) {MOSCAP} nfin={C2_NFIN}")
    L.append("ends vco_x_c_dac")
    L.append("")
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    gen()
