#!/usr/bin/env python3
"""Generate sim/pll_ssbb_main.scs — ref2 SS-BB-ADPLL closed-loop top level.

Signal flow (ref2_ssbb_plan.md §4):
  REF(100M) -> dtc_10b_ss(CODE<-frac_acc, FCW=0 integer) -> CKR
  CKR,DIV4 -> bbpd -> BB/BB_DZ -> dlf(kp,ki<-gs) -> code[15:0]
  code[15:9] -> dac7 -> VC1 (coarse varactor bulk, nfin=24)
  code[8:0]  -> dac9 -> VC2 (fine varactor bulk, nfin=2)
  OUTP -> Rbuf -> 2-stage inverter buffer -> OUTPB -> div4 -> DIV4 -> (bbpd|afc)
  REF,DIV4 -> afc(target=320) -> A[6:0]+AFC_DONE -> (dlf base load | gs enable)
  LDO ldo_05: 1V -> 0.5V core supply VDDC

Usage: python3 tools/gen_ssbb_top.py [stop]   (default 300n)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PDK = 'include "/home/lib/tsmc_12nm_installed/pdk/models/toplevel.scs" section=top_tt'

INV = ("    {name}_n ({out} {in} VSS VSS) nch_svt_mac l=16n nfin=2 w=58n multi=1 "
       "nf=4 sd=74n sa=90n sb=90n ploda1=16n ploda2=0 ploda3=0 plodb1=16n "
       "plodb2=0 plodb3=0 nf_flag=1 smbt=1M smbb=1M dinsaflag=0 ppitch=0 "
       "spot=103n spob=103n spotl1=103n spobl1=103n spotl2=103n spobl2=103n "
       "spotr1=103n spobr1=103n spotr2=103n spobr2=103n\n"
       "    {name}_p ({out} {in} VDD VDD) pch_svt_mac l=16n nfin=2 w=58n multi=1 "
       "nf=4 sd=74n sa=90n sb=90n ploda1=16n ploda2=0 ploda3=0 plodb1=16n "
       "plodb2=0 plodb3=0 nf_flag=1 smbt=1M smbb=1M dinsaflag=0 ppitch=0 "
       "spot=103n spob=103n spotl1=103n spobl1=103n spotl2=103n spobl2=103n "
       "spotr1=103n spobr1=103n spotr2=103n spobr2=103n")


def gen(stop="300n", fcw="0.0", mode="v4", lean=False, afc_target=320):
    L = []
    a = L.append
    a("// pll_ssbb_main.scs — generated by tools/gen_ssbb_top.py (ref2 SS-BB-ADPLL)")
    a("// integer channel 100M/8G (FCW=0); AFC target=320 = 2G*160ns window")
    if mode == "v3":
        a("// V3 AFC-only closed loop: no BBPD/DLF/GS; AFC code -> dac7 -> VC1,")
        a("// VC2 fixed 0.25V (KVCO1 sweep reference). Expect code 64->~80,")
        a("// AFC_DONE ~1.3us, fVCO 8.00G +-25MHz (count tol).")
    a("simulator lang=spectre")
    a("")
    a(PDK)
    # decoder VA must be defined BEFORE the dtc subckt (Xdec inside) is read,
    # so all ahdl_includes precede the scs includes
    vas = ["afc", "dac7", "div4"]
    if mode == "v4":
        vas += ["bbpd", "dlf", "dac9", "gs", "frac_acc", "dtc_code"]
    for m in vas:
        a(f'ahdl_include "netlist/va/pll_{m}.va"')
    a('include "netlist/inc/ldo_05.scs"')
    a('include "netlist/inc/vco_c_dac.scs"')
    if mode == "v4":
        a('include "netlist/inc/dtc_10b_ss.scs"')
    a("")
    a("// --- sources ---")
    a("Vvdd (VDD 0) vsource dc=0.8")
    a("Vvss (VSS 0) vsource dc=0")
    a("Vref (REF 0) vsource type=pulse val0=0 val1=0.8 period=10n width=5n"
      " rise=10p fall=10p")
    a("Vv1v (V1V 0) vsource dc=1.0")
    a("Vvbg (VBG 0) vsource dc=0.5")
    a("Vvbl (VBL 0) vsource dc=0.62")
    a("")
    a("// --- LDO: 1.0V -> 0.5V VCO core supply ---")
    a("Xldo (VDD V1V VBG VBL VDDC VSS) ldo_05")
    a("")
    a("// --- reference path: REF -> DTC(CODE) -> CKR ---")
    if mode == "v4":
        a("Xacc (REF " + " ".join(f"D{i}" for i in range(10)) + ")"
          f" pll_frac_acc FCW={fcw}")
        a("Xdtc (REF CKR VDD VSS " + " ".join(f"D{i}" for i in range(10)) + ")"
          " dtc_10b_ss")
    a("")
    if mode == "v4":
        a("// --- BBPD + DLF + DACs ---")
        a("Xbbpd (CKR DIV4 BB BB_DZ) pll_bbpd vth=0.4 Tdz=50p")
        a("Xdlf (CKR BB AFC_DONE "
          + " ".join(f"A{i}" for i in range(7))
          + " KP KI " + " ".join(f"C{i}" for i in range(16)) + ") pll_dlf")
        a("Xdac1 (VC1 " + " ".join(f"C{i}" for i in range(9, 16)) + ")"
          " pll_dac7 vmax=0.5")
        a("Xdac2 (VC2 " + " ".join(f"C{i}" for i in range(0, 9)) + ")"
          " pll_dac9 vmax=0.5")
    else:
        a("// V3: AFC code directly through the ideal coarse DAC")
        a("Xdac1 (VC1 " + " ".join(f"A{i}" for i in range(7)) + ")"
          " pll_dac7 vmax=0.5")
        a("Vc2 (VC2 0) vsource dc=0.25")
    a("")
    a("// --- VCO + buffer + /4 feedback ---")
    a("// vco_x_c_dac 'VDD' port = tank supply -> tie to 0.5V VDDC (as the dual")
    a("// wrapper does: Xa(VDDC ...)); subckt VDDC port is unused inside, tie too")
    a("Xvco (VDDC VDDC VSS OUTP OUTN VC1 VC2) vco_x_c_dac")
    a("Rbuf (OUTP BUFFIN) resistor r=1k")
    a("// two-stage 0.8V-domain inverter buffer (proven in hyb top)")
    a(INV.format(**{"name": "Minvb1", "out": "NBUF1", "in": "BUFFIN"}))
    a(INV.format(**{"name": "Minvb2", "out": "OUTPB", "in": "NBUF1"}))
    a("Xdiv4 (OUTPB DIV4) pll_div4 vth=0.5")
    a("")
    a("// --- AFC + GS ---")
    a("// integer: target=320 (8G/4*160ns); fractional 8.05G: 322")
    a("Xafc (REF DIV4 " + " ".join(f"A{i}" for i in range(7))
      + f" AFC_DONE CNTOUT) pll_afc target={afc_target} K=16")
    if mode == "v4":
        a("Xgs (REF BB BB_DZ AFC_DONE G0 G1 G2 KP KI) pll_gs W=128 THR=4")
    a("")
    a("plltran tran stop=" + stop + " maxstep=2p errpreset=liberal"
      " method=gear2only skipdc=yes ic=\"OUTP=0.45\" ic=\"OUTN=0.0\"")
    if mode == "v4" and lean:
        # long-run save list: 9 signals (27 -> ~5GB at 10us; 9 -> ~1.7GB).
        # fVCO/jitter from DIV4 edges; A-code settles at 96 and is not resaved.
        a("save REF BB BB_DZ VC1 VC2 DIV4 AFC_DONE KP KI")
    elif mode == "v4":
        a("save REF CKR BB BB_DZ VC1 VC2 DIV4 OUTP OUTPB VDDC AFC_DONE"
          " KP KI G0 G1 G2 C9 C15 CNTOUT " + " ".join(f"A{i}" for i in range(7)))
    else:
        a("save REF VC1 VC2 DIV4 OUTP OUTPB VDDC AFC_DONE CNTOUT"
          " " + " ".join(f"A{i}" for i in range(7)))
    a("saveOptions options save=selected")
    a("")
    return "\n".join(L)


if __name__ == "__main__":
    stop = sys.argv[1] if len(sys.argv) > 1 else "300n"
    fcw = sys.argv[2] if len(sys.argv) > 2 else "0.0"
    mode = sys.argv[3] if len(sys.argv) > 3 else "v4"
    lean = (sys.argv[4] == "lean") if len(sys.argv) > 4 else False
    afc_target = int(sys.argv[5]) if len(sys.argv) > 5 else (322 if float(fcw) else 320)
    if mode == "v3":
        name = "pll_ssbb_v3.scs"
    elif lean:
        name = "pll_ssbb_main_10u.scs"
    elif float(fcw):
        name = "pll_ssbb_frac.scs"
    else:
        name = "pll_ssbb_main.scs"
    out = ROOT / "sim" / name
    out.write_text(gen(stop, fcw, mode, lean, afc_target))
    print(f"wrote {out} stop={stop} FCW={fcw} mode={mode} lean={lean} afc_target={afc_target}")
