#!/usr/bin/env python3
"""Build sim/pll_step2_main_c_hyb.scs — Plan C closed loop, hybrid deck.

- schematic-derived (verified) subckts: spd_x / cmp_x / gm_x / dtc_10b
  extracted from tools/tb_adpll_top_sch_netlist.scs (si export)
- new scs modules: vco_dual_8g_c (vco_c.scs) + ldo_05
- top level: sim/pll_step2_main_c.scs (Plan C wiring, minus the inc includes)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCH = ROOT / "tools" / "tb_adpll_top_sch_netlist.scs"
TOP_C = ROOT / "sim" / "pll_step2_main_c.scs"
OUT = ROOT / "sim" / "pll_step2_main_c_hyb.scs"

WANT = ["spd_x", "cmp_x", "gm_x", "dtc_10b"]  # schematic-verified blocks


def subckt_body(text, name):
    m = re.search(rf"subckt\s+{name}\s+[^\n]*\n(.*?)ends\s+{name}", text, re.S)
    if not m:
        print(f"subckt {name} not found in export")
        sys.exit(1)
    return m.group(0)


def main():
    sch = SCH.read_text()
    top = TOP_C.read_text()

    # drop the inc includes for blocks provided by the schematic export
    top = top.replace('include "dtc_10b.scs"\n', "")
    top = top.replace('include "spd_cmp_gm.scs"\n', "")
    top = top.replace("// plan A': decoder moved INSIDE dtc_10b (paper architecture); only 11 external ports\n", "")

    header = (
        "// pll_step2_main_c_hyb.scs — generated by tools/build_hyb_c.py\n"
        "// Plan C closed loop: schematic-exported spd/cmp/gm/dtc_10b + new\n"
        "// scs vco_dual_8g_c (0.5V core, VAR banks) + ldo_05\n\n"
    )
    blocks = "\n".join(subckt_body(sch, n) + "\n" for n in WANT)
    OUT.write_text(header + top + "\n" + blocks)
    print(f"wrote {OUT} ({len((header + top + blocks).splitlines())} lines)")
    for n in WANT:
        print(f"  {n}: inlined")


if __name__ == "__main__":
    main()
