#!/usr/bin/env python3
"""Generate sim/ref3/v3/<run>/main.scs — ref3 ADPLL_ALG V3 integer closed loop.

Signal flow (ref3_adpll_alg_plan.md §4):
  REF(100M) -> dtc_10b_ss(CODE<-cal_kdtc) -> CKR
  OUTP -> Rbuf -> 2-stage buffer -> OUTPB -> mmd_ps(ratio<-dsm_fb) -> CKFB
                                             OUTPB -> divn(/16) -> CK16
  CKR,CKFB -> tdc_beh -> one-hot/thermometers -> pfd -> phe
  fsm: IDEL->AFC->FLL->PLL->LOCK on afc_done/freq_lock/phase_lock
  afc6(CK16,thr=7) PB[5:0] -> lpf AFC-slave ; fll(CK16,thr=8) -> FCTRL
  lpf -> AB[8:0] -> dac9b -> VC1 (coarse, KVCO_A=0.607MHz/LSB @0.5V)
       -> FR[25:0] -> dsm_dco -> FC[3:0] -> dac9b(low 4b) -> VC2 (fine)
  cal_kdtc(phe,q_err) -> DT[9:0] ; cal_dcodcc(sel) -> DCOMP ; refdcc off (D)
  vco_x_c_dac (both supply pins on VDDC) + ldo_05 core supply

Scaled stage-A windows for the local run (documented deviations, see
progress.md V3 entry):
  - afc6 thr=7 (spec 8): window 1.28us, 1 edge = 12.5MHz vs Pbank step 4.86MHz
  - fll thr=8 (spec 9): window 2.56us, 1 edge = 6.25MHz
  - fll ftol=2 (spec 1): absorbs afc +-1-edge parking residual (= +-2 edges
    at fll thr=8); PLL pulls the rest via phe
  - lock_thr=0.02 (spec 0.01): VA TDC quantization is 1/64 cycle = 0.0156,
    spec threshold would require phe == 0 exactly on every REF edge

Usage: python3 tools/gen_ref3_top.py [smoke|full]   (default full)
  smoke -> stop=4.5u, wide save (catches first AFC code move at ~3.9u)
  full  -> stop=20u, lean save (LOCK predicted ~14.5u)
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VA = ROOT / "netlist" / "va"
INC = ROOT / "netlist" / "inc"
V3 = ROOT / "sim" / "ref3" / "v3"
PDK = 'include "/home/lib/tsmc_12nm_installed/pdk/models/toplevel.scs" section=top_tt'

# all ahdl_includes precede the scs includes: dtc_10b_ss.scs instantiates Xdec
# (pll_dtc_code.va), which must already be defined (SFE-23 lesson, ref2 V2b)
VAS = ["pll_dsm_fb.va", "pll_mmd_ps.va", "pll_divn.va", "pll_tdc_beh.va",
       "pll_pfd.va", "pll_fll.va", "pll_afc6.va", "pll_fsm.va",
       "pll_lockdet.va", "pll_lpf.va", "pll_dsm_dco.va", "pll_cal_kdtc.va",
       "pll_cal_dcodcc.va", "pll_dac9b.va", "pll_dtc_code.va"]
INCS = ["ldo_05.scs", "vco_c_dac.scs", "dtc_10b_ss.scs"]

INV = ("    {name}_n ({out} {in} VSS VSS) nch_svt_mac l=16n nfin=2 w=58n multi=1 "
       "nf=4 sd=74n sa=90n sb=90n ploda1=16n ploda2=0 ploda3=0 plodb1=16n "
       "plodb2=0 plodb3=0 nf_flag=1 smbt=1M smbb=1M dinsaflag=0 ppitch=0 "
       "spot=103n spob=103n spotl1=103n spobl1=103n spotl2=103n spobl2=103n "
       "spotr1=103n spobr1=103n spotr2=103n spobr2=103n\n"
       "    {name}_p ({out} {in} VDD VDD) pch_svt_mac l=16n nfin=2 w=58n multi=1 "
       "nf=4 sd=74n sa=90n sb=90n ploda1=16n ploda2=0 ploda3=0 plodb1=16n "
       "plodb2=0 plodb3=0 nf_flag=1 smbt=1M smbb=1M dinsaflag=0 ppitch=0 "
       "spot=103n spob=103n spotl1=103n spobl1=103n spotl2=103n spobl2=103n "
       "spotr1=103n spobr1=103n spotr2=103n spobr2=103n")

SAVE_LEAN = ("save REF CK16 CNTOUT PHE QERR SELF VC1 VC2 VDDC FSTATE FCTRL"
             " FQLK PHLK AFCD")
SAVE_SMOKE = ("save REF CKR CKFB CK16 CNTOUT PHE QERR SELF VC1 VC2 VDDC FSTATE"
              " FCTRL FQLK PHLK AFCD ENA ENF ENP OUTPB AB8 AB7 AB6 KDBG")


def bus(p, n):
    return " ".join(f"{p}{i}" for i in range(n))


def gen(stop, save):
    L = []
    a = L.append
    a("// main.scs — ref3 ADPLL_ALG V3 integer closed loop (FCW=80, 100M/8G)")
    a("// generated by tools/gen_ref3_top.py")
    a("// scaled windows: afc thr=7/fll thr=8 (spec 8/9), fll ftol=4 (spec 1;")
    a("//   absorbs afc +-1-edge parking residual up to +-25MHz = +-4 fll edges),")
    a("//   lock_thr=0.02 (spec 0.01; VA TDC quantum 1/64 = 0.0156)")
    a("simulator lang=spectre")
    a(PDK)
    a('ahdl_include "constants.vams"')
    a('ahdl_include "disciplines.vams"')
    for f in VAS:
        a(f'ahdl_include "{f}"')
    for f in INCS:
        a(f'include "{f}"')
    a("")
    a("// --- sources ---")
    a("Vvdd (VDD 0) vsource dc=0.8")
    a("Vvss (VSS 0) vsource dc=0")
    a("Vref (REF 0) vsource type=pulse val0=0 val1=0.8 period=10n width=5n"
      " rise=10p fall=10p")
    a("Vv1v (V1V 0) vsource dc=1.0")
    a("Vvbg (VBG 0) vsource dc=0.5")
    a("Vvbl (VBL 0) vsource dc=0.62")
    a("// FSM reset released at 20n (VCO/LDO startup before IDEL counting)")
    a("Vrstn (RSTN 0) vsource type=pulse val0=0 val1=0.8 period=1m width=1m"
      " delay=20n rise=10p fall=10p")
    a("// dsm_fb rcomp: ref-doubler DCC compensation input, off (decision D)")
    a("Vrcomp (RCOMP 0) vsource dc=0")
    a("")
    a("// --- LDO 1.0V -> 0.5V VCO core supply ---")
    a("Xldo (VDD V1V VBG VBL VDDC VSS) ldo_05")
    a("")
    a("// --- FSM + lock detect ---")
    a("Xfsm (REF RSTN AFCD FQLK PHLK ST0 ST1 ST2 ENA ENF ENP FSTATE)"
      " pll_fsm idle_wait=4")
    a("Xlock (REF PHE PHLK) pll_lockdet lock_thr=0.02")
    a("")
    a("// --- feedback DSM + MMD + fixed /16 tap ---")
    a("Xdsmf (REF RCOMP " + bus("P", 13) + " QERR SELF) pll_dsm_fb"
      " FCW=80.0 dsm_fb_mode=0")
    a("Xmmd (OUTPB " + bus("P", 13) + " SELF CKFB) pll_mmd_ps ninit=80")
    a("// pll_divn toggles every N RISING edges -> full period = 2N VCO cycles;")
    a("// N=8 gives the true /16 tap (500M @8G) matching afc6/fll D=16")
    a("Xdivn (OUTPB CK16) pll_divn N=8")
    a("")
    a("// --- reference path: REF -> DTC(CODE from cal_kdtc) -> CKR ---")
    a("Xdtc (REF CKR VDD VSS " + bus("DT", 10) + ") dtc_10b_ss")
    a("")
    a("// --- TDC + PFD ---")
    a("Xtdc (CKR CKFB " + bus("OHA", 16) + " " + bus("OHB", 16) + " "
      + bus("CA", 16) + " " + bus("CB", 16) + " " + bus("FT", 16)
      + " ARB) pll_tdc_beh")
    a("Xpfd (" + bus("CA", 16) + " " + bus("CB", 16) + " " + bus("FT", 16)
      + " ARB " + bus("OHA", 16) + " " + bus("OHB", 16)
      + " PHE TCODE) pll_pfd")
    a("")
    a("// --- AFC + FLL (both count CK16 = fVCO/16) ---")
    a("Xafc (REF CK16 ENA " + bus("PB", 6) + " AFCD CNTOUT) pll_afc6"
      " FCW=80.0 thr=7 D=16")
    a("Xfll (REF CK16 ENF FCTRL FQLK) pll_fll FCW=80.0 thr=8 D=16 ftol=4")
    a("")
    a("// --- LPF + coarse/fine DACs + DCO DSM ---")
    a("Xlpf (REF PHE FCTRL ENA ENF ENP PHLK " + bus("PB", 6) + " "
      + bus("AB", 9) + " " + bus("FR", 26) + ") pll_lpf")
    a("Xdacab (VC1 " + bus("AB", 9) + ") pll_dac9b vmax=0.5")
    a("Xdsmd (REF " + bus("FR", 26) + " " + bus("FC", 4) + ") pll_dsm_dco"
      " dsm_dco_mode=0")
    a("// fine DAC: low 4 bits = DSM thermo, upper 5 bits grounded")
    a("Xdacfb (VC2 " + bus("FC", 4) + " VSS VSS VSS VSS VSS) pll_dac9b"
      " vmax=0.5")
    a("")
    a("// --- background calibrations (kdtc + dco duty; refdcc off) ---")
    a("Xcalk (REF PHE QERR DCOMP ENP " + bus("DT", 10) + " KDBG)"
      " pll_cal_kdtc")
    a("Xcald (REF PHE SELF ENP DCOMP DDBG) pll_cal_dcodcc")
    a("")
    a("// --- VCO + buffer (vco_x_c_dac pin1 = tank supply -> VDDC node) ---")
    a("Xvco (VDDC VDDC VSS OUTP OUTN VC1 VC2) vco_x_c_dac")
    a("Rbuf (OUTP BUFFIN) resistor r=1k")
    a(INV.format(**{"name": "Minvb1", "out": "NBUF1", "in": "BUFFIN"}))
    a(INV.format(**{"name": "Minvb2", "out": "OUTPB", "in": "NBUF1"}))
    a("")
    a('plltran tran stop=' + stop + ' maxstep=2p errpreset=liberal'
      ' method=gear2only skipdc=yes strobeperiod=50p'
      ' ic="OUTP=0.45" ic="OUTN=0.0"')
    a(save)
    a("saveOptions options save=selected")
    a("")
    return "\n".join(L)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "full"
    if mode == "smoke":
        d, stop, save = V3 / "smoke", "4.5u", SAVE_SMOKE
    else:
        d, stop, save = V3 / "main", "20u", SAVE_LEAN
    d.mkdir(parents=True, exist_ok=True)
    (d / "main.scs").write_text(gen(stop, save))
    for f in VAS + ["constants.vams", "disciplines.vams"]:
        shutil.copy(VA / f, d / f)
    for f in INCS:
        shutil.copy(INC / f, d / f)
    print(f"wrote {d}/main.scs stop={stop} mode={mode}")


if __name__ == "__main__":
    main()
